Vocab size : 53
---------------------Starting training---------------------
865
1344
765
522
1117
823
1688
1088
589
521
1296
1010
647
687
601
793
638
615
515
999
533
1151
871
840
1124
619
905
629
1872
2467
929
1334
1549
907
1100
796
529
1409
627
671
1252
718
923
1180
697
1341
557
674
  1%|█▎                                                                                                                                                                             | 2/279 [00:01<02:54,  1.59it/s]
638
1502
567
1357
879
859
1298
566
1226
581
1098
891
938
940
618
601
599
515
823
543
1731
645
547
728
786
  1%|██▌                                                                                                                                                                            | 4/279 [00:02<02:21,  1.94it/s]
Traceback (most recent call last):
  File "train.py", line 253, in <module>
    step(model, optimizer, scheduler, train_loader, test_dataset, device, epoch, path, best_loss = 1000)
  File "train.py", line 37, in step
    for idx, (context,targets) in enumerate(train_loader):
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/dataset.py", line 54, in __getitem__
    start_index = random.randint(0, len(dialogue) - self.ctx_len - 1)
  File "/Users/hugo/.pyenv/versions/3.8.18/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/Users/hugo/.pyenv/versions/3.8.18/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, -5, -5)